[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "jm_utils"
version = "0.1.0"
description = "Utilities i use frecuntly"
authors = ["Jorge Monti"]